In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
X = x.reshape(3,4)

In [6]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
y = torch.tensor([[1,2,3,4],[5,6,7,8]])
y

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [8]:
a = torch.zeros((3,3,3))
a

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [11]:
x = torch.tensor([1.0,2,4,8])
x

tensor([1., 2., 4., 8.])

In [13]:
x = torch.arange(12,dtype = torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[3,4,2,1]])
x,y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [3., 4., 2., 1.]]))

In [14]:
a = torch.cat((x,y),dim = 0)
b = torch.cat((x,y),dim = 1)

In [16]:
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  2.,  1.]])

In [17]:
b

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  3.,  4.,  2.,  1.]])

In [24]:
a[-3:-1]

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.]])

In [29]:
z = torch.zeros_like(a)
print(f'id(z): {id(z)}')
z = a + torch.ones_like(a)
print(f'id(z): {id(z)}')
z[:] = a + torch.ones_like(a)
print(f'id(z): {id(z)}')

id(z): 2072749379312
id(z): 2072749385712
id(z): 2072749385712


In [32]:
before = id(a)
a += torch.ones_like(a)
after = id(a)
a = a+ torch.ones_like(a)
print(f'before:{before}\n after:{after} \n id(a):{id(a)}')

before:2072707745248
 after:2072707745248 
 id(a):2072702594448


In [33]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [34]:
import numpy as np


In [36]:
a = np.arange(1,3,0.5)
a = np.array([1,2,3,])
a

array([1, 2, 3])