##### 标量

In [3]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(4.0)

x+y

tensor(7.)

##### 向量

In [5]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [6]:
x[3]

tensor(3)

In [7]:
len(x)

4

In [8]:
x.shape

torch.Size([4])

##### 矩阵

In [10]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [11]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [13]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

##### 张量

In [14]:
X = torch.arange(24).reshape(2,3,4)

##### 张量算法的基本性质

In [16]:
A = torch.arange(20,dtype = torch.float32).reshape(5,4)
B = A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [17]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [18]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X ,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

##### 降维

In [19]:
X = torch.arange(4,dtype = torch.float32)
x,x.sum()

(tensor([0, 1, 2, 3]), tensor(6))

In [20]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [21]:
A_sum_axis0 = A.sum(axis = 0)
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [22]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [23]:
A.sum(axis = [0,1])

tensor(190.)

In [24]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [25]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [26]:
sum_A = A.sum(axis = 1, keepdims = True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [27]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [29]:
A1 = A.cumsum(axis = 0)
A2 = A.cumsum(axis = 1)
A1,A2

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.],
         [12., 25., 39., 54.],
         [16., 33., 51., 70.]]))

In [32]:
B = torch.ones(4, 3)
torch.mm(A, B).shape

torch.Size([5, 3])

##### 范数

In [34]:
u= torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [35]:
torch.abs(u).sum()

tensor(7.)

In [36]:
torch.norm(torch.ones((4,9)))

tensor(6.)