In [1]:
import torch
from IPython import display
from d2l import torch as d2l

batch_size = 256
train_iter,test_iter = d2l.load_data_fashion_mnist(batch_size)

In [2]:
num_inputs = 784
num_outputs = 10

W = torch.normal(0,0.01,size = (num_inputs,num_outputs),requires_grad =True)
b = torch.zeros(num_outputs,requires_grad=True)

In [3]:
X = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
X.sum(0,keepdim=True),X.sum(1,keepdim = True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [4]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1,keepdim = True)
    return X_exp/partition

In [5]:
X = torch.normal(0, 1, (2, 5))
X_prob = softmax(X)
X_prob, X_prob.sum(1)

(tensor([[0.0471, 0.0498, 0.0141, 0.2353, 0.6537],
         [0.5057, 0.0568, 0.2002, 0.1119, 0.1254]]),
 tensor([1., 1.]))

In [6]:
def net(X):
    return softmax(torch.matmul(X.reshape((-1,W.shape[0])),W)+b)

In [7]:
y = torch.tensor([0,2])
y_hat = torch.tensor([[0.1,0.3,0.6],[0.3,0.2,0.5]])
y_hat[[0,1],y]

tensor([0.1000, 0.5000])

In [8]:
def cross_entorpy(y_hat,y):
    return -torch.log(y_hat[range(len(y_hat)),y])

cross_entorpy(y_hat,y)

tensor([2.3026, 0.6931])

In [9]:
def accuracy(y_hat,y):
    if len(y_hat.shape) >1 and y_hat.shape[1]>1:
        y_hat = y_hat.argmax(axis=1)
    cmp = y_hat.type(y.dtype) == y
    return float(cmp.type(y.dtype).sum())

In [13]:
y_hat,y_hat.argmax(axis=1)

(tensor([[0.1000, 0.3000, 0.6000],
         [0.3000, 0.2000, 0.5000]]),
 tensor([2, 2]))

In [19]:
def evaluate_accuracy(net,data_iter):
    if isinstance(net,torch.nn.Module):
        net.eval()
    metric = Accummulator(2)
    for X,y in data_iter:
        metric.add(accuracy(net(X),y),y.numel()
    return metric[0] / metric[1]

In [20]:
class Accumulator:
    def __init__(self,n):
        self.data = [0.0] * n
    def add(self,*args):
        self.data = [a + float(b) for a,b in zip[self.data,args]]
    def reset(self):
        self.data = [0.0] * len(self.data)
    def __getitem__(self, idx):
        return self.data[idx]

In [29]:
f'{evaluate_accuracy(net, test_iter)}'

'None'